export const ADD_INFOS = 'ADD-INFOS';
export const COMPLETE = 'COMPLETE';
export const MULTIPLE_CHOICE = 'MULTIPLE_CHOICE';
export const ONE_CHOICE = 'ONE_CHOICE';
export const INPUT_ANSWER = 'INPUT_ANSWER';
export const IS_COMPLETE = 'IS_COMPLETE';
export const COMPUTE_SCORE = 'COMPUTE_SCORE';
export const COMPUTE_TOTAL_SCORE = 'COMPUTE_TOTAL_SCORE';
